# vi: se sw=2 sts=2 ts=2 et:
image: docker.adeo.no:5000/fo/mia
replicas:
  min: 2
  max: 3
port: 8800

healthcheck:
  liveness:
    path: /internal/actuator/health
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isReady
    initialDelay: 60
    timeout: 10

team: bos

alertProfiles:
  - basic
