# vi: se sw=2 sts=2 ts=2 et:
image: docker.adeo.no:5000/fo/mia
replicas:
  min: 2
  max: 3
port: 8800
healthcheck:
  liveness:
    path: /mia/internal/isAlive
    initialDelay: 60
  readiness:
    path: /mia/internal/isReady
    initialDelay: 60

fasitResources:
  used:
  - alias: stilling.solr
    resourceType: baseurl
    propertyMap:
      url: STILLING_SOLR_URL

  - alias: stillingsok.link
    resourceType: baseurl
    propertyMap:
      url: STILLINGSOK_LINK_URL

  - alias: miasolr.solr.ledigestillingercore
    resourceType: restservice
    propertyMap:
      url: MIASOLR_SOLR_LEDIGESTILLINGERCORE_URL

  - alias: miasolr.solr.ledigestillingercore
    resourceType: restservice
    propertyMap:
      url: MIASOLR_SOLR_ARBEIDSLEDIGECORE_URL

  - alias: miasolr.elastic
    resourceType: baseurl
    propertyMap:
      url: MIASOLR_ELASTIC_URL

  - alias: mia_elasticsearch_user
    resourceType: credential
    propertyMap:
      username: MIASOLR_ELASTIC_USER
      password: MIASOLR_ELASTIC_PSW
