# vi: se sw=2 sts=2 ts=2 et:
image: docker.adeo.no:5000/fo/mia
replicas:
  min: 2
  max: 3
port: 8800

healthcheck:
  liveness:
    path: /internal/actuator/health
    initialDelay: 60
    timeout: 10
  readiness:
    path: /internal/isReady
    initialDelay: 60
    timeout: 10

resources:
  limits:
    cpu: 3
    memory: 768Mi
  requests:
    memory: 512Mi


prometheus:
  enabled: true
  path: /internal/actuator/prometheus

team: bos

fasitResources:
  used:
  - alias: mia_elasticsearch_user
    resourceType: credential
    propertyMap:
      username: MIA_ELASTIC_USER
      password: MIA_ELASTIC_PSW

  - alias: appdynamics
    resourceType: applicationproperties

  - alias: loadbalancer:mia
    resourceType: loadbalancerconfig

  - alias: unleash-api
    resourceType: restservice


alertProfiles:
  - basic
