server:
  use-forward-headers: true
  port: 8800
  compression:
    enabled: true
    mime-types: text/html,text/xml,text/plain,text/css,text/javascript,application/javascript,application/json
    min-response-size: 1024

spring:
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB

mia:
  elastic:
    hostname: tpa-miasecsok-elasticsearch.tpa.svc.nais.local
    port: 9200
    scheme: http

management:
  endpoints:
    web:
      base-path: /internal/actuator
      exposure:
        include:
          - prometheus
          - health
          - info
  metrics:
    distribution:
      percentiles:
        http.server.requests: [0.5,0.95]
      percentiles-histogram:
        http.server.requests: true
  endpoint:
    health:
      show-details: always

