version: 2
jobs:
  build-frontend:
    docker:
      - image: circleci/node:8.9.4

    working_directory: ~/mia/src/frontend
    steps:
      - checkout:
          path: ~/mia

      - restore_cache:
          keys:
          - v1-dependencies-{{ checksum "package.json" }}

      - run: npm install

      - save_cache:
          paths:
            - node_modules
          key: v1-dependencies-{{ checksum "package.json" }}

      - run: npm run test
      - run: npm run build

  build-backend:
    docker:
      - image: circleci/java:8-jdk

    working_directory: ~/mia
    steps:
      - checkout:
          path: ~/mia

      - run: mvn verify

workflows:
  version: 2
  commit:
    jobs:
      - build-frontend
      - build-backend
